### PR TITLE
fix: pending transaction should be not be "success"

### LINKED ISSUE #2927: Timeout payment reported as successful
When ln send payment are timing out, we currently says they are successful, which is incorrect

### PR DESCRIPTION
**Pull request by nicolasburtey**
the issue is that the use case for queued transaction is conflated with the pending lightning transaction that may fail

fix #2927

### CODE REVIEW

File: app/screens/send-bitcoin-screen/send-bitcoin-completed-screen.tsx [hunk 1]
```diff
@@ -92,26 +106,43 @@ const SendBitcoinSuccessScreen: React.FC<Props> = ({ route }) => {
...
+  }
+
+  const SuccessText = () => {
+    switch (status) {
+      case "SUCCESS":
+        return LL.SendBitcoinScreen.success()
+      case "QUEUED":
+        return LL.TransactionDetailScreen.txNotBroadcast({
+          countdown: formatTimeToMempool(
+            timeToMempool(arrivalAtMempoolEstimate as number),
```
Comment (nicolasburtey) [inline app/screens/send-bitcoin-screen/send-bitcoin-completed-screen.tsx:127]: @sandipndev I refactored `formatTimeToMempool` and needed to wrap the function with `timeToMempool`. this will fix the `27,123 minutes to confirm`

**Review by sandipndev — APPROVED** [review]
