### PR TITLE
fix: Add param to get full uri without prefix

### LINKED ISSUE #155: Onchain bitcoin address copy with bitcoin: prefix
**Describe the bug**
when you copy the bitcoin address it copies with `bitcoin:` prefix

**To Reproduce**
1. Go to Receive screen
2. Swipe to get an onchain address
3. Tap on QR code

**Expected behavior**
copy the address without `bitcoin:` prefix

**Smartphone:**
 - Device: iPhoneXs
 - OS: 14.6
 - Version 1.4.9 build 259

### PR DESCRIPTION
**Pull request by mfferreira**
Fixes #155

Added an extra param to be able to get the full uri with (default) or without the `bitcoin:` prefix.

### CODE REVIEW

File: app/screens/receive-bitcoin-screen/ReceiveBitcoinScreenTypes.d.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+interface IGetFullUri {
```
Comment (jrbuhl93) [inline app/screens/receive-bitcoin-screen/ReceiveBitcoinScreenTypes.d.ts:1]: Maybe this should just be a type  instead of an interface since we aren't extending it? `GetFullUriInput`

Comment (mfferreira) [reply app/screens/receive-bitcoin-screen/ReceiveBitcoinScreenTypes.d.ts:1]: Sure, I can update it to type.
Would that be the rule of thumb for using types or interfaces?

Comment (jrbuhl93) [reply app/screens/receive-bitcoin-screen/ReceiveBitcoinScreenTypes.d.ts]: It's a complicated topic [it seems](https://stackoverflow.com/questions/37233735/typescript-interfaces-vs-types), and we shouldn't take my word as gospel. @samerbuna

Comment (jrbuhl93) [reply app/screens/receive-bitcoin-screen/ReceiveBitcoinScreenTypes.d.ts]: It's possible I was wrong because further down in [the link](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces) it says: `For the most part, you can choose based on personal preference, and TypeScript will tell you if it needs something to be the other kind of declaration. If you would like a heuristic, use interface until you need to use features from type.`

Comment (mfferreira) [reply app/screens/receive-bitcoin-screen/ReceiveBitcoinScreenTypes.d.ts]: Indeed, for the most part it's personal preference, so it's fine either way. I'll just follow the project setup 👌

My force of habit is to use `interface` when it's literally an interface to talk to some code.

**Review by jrbuhl93 — APPROVED** [review]
