### PR TITLE
fix: Fixed receive screen bugs

### LINKED ISSUE #526: Paid invoice falsely says expired
A2D07E35-1BF0-43F2-A470-29E7523DA79F-4529-00001774D346640C

### PR DESCRIPTION
**Pull request by daviroo**
Fixes #526 , #552 and #540

### CODE REVIEW

File: app/screens/receive-bitcoin-screen/receive-usd.tsx [hunk 1]
```diff
@@ -145,6 +146,45 @@ const ReceiveUsd = () => {
...
+            () => setStatus("expired"),
+          )
+        }
+      }
+      appState.current = nextAppState
+    })
+    return () => {
+      subscription.remove()
+    }
+    // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (UncleSamtoshi) [inline app/screens/receive-bitcoin-screen/receive-usd.tsx:176]: Why not include ```setStatus``` as one of the dependencies?

File: app/hooks/use-countdown-timer.ts [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+    newCallback?: () => void,
+  ) => {
+    setTimeLeft(seconds)
+    if (completedCallback) {
+      completedCallback()
+    }
+    setCompletedCallback(() => newCallback)
+  }
+
+  const stopCountdownTimerAndExecuteCallback = (newCallback?: () => void) => {
```
Comment (UncleSamtoshi) [inline app/hooks/use-countdown-timer.ts:69]: I think this should be called ```clearCountdown...``` and I dont think it makes sense to pass in a new callback for stopping the countdown timer because it will just be executed immediately anyway. The function that calls this function can just execute the callback itself if it wants to.

File: app/hooks/use-countdown-timer.ts [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+  }
+
+  const resetCountdownTimer = (seconds: number, newCallback?: () => void) => {
+    setTimeLeft(seconds)
+    if (newCallback) {
+      setCompletedCallback(() => newCallback)
+    }
+  }
+
+  const resetCountdownTimerAndExecuteCallback = (
```
Comment (UncleSamtoshi) [inline app/hooks/use-countdown-timer.ts:58]: Maybe rename this to ```resetCountdownTimerAndExecuteExistingCallback```?

File: app/hooks/use-countdown-timer.ts [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+  }, [timeLeft, completedCallback])
+
+  const startCountdownTimer = (seconds: number, callback?: () => void) => {
+    setTimeLeft(seconds)
+    if (callback) {
+      setCompletedCallback(() => callback)
+    }
+  }
+
+  const stopCountdownTimer = () => {
```
Comment (UncleSamtoshi) [inline app/hooks/use-countdown-timer.ts:47]: This will trigger the callback which I dont think is the expected behavior. ```stopCountdownTimer``` to me implies that you are pausing the time at its current value.

File: app/screens/receive-bitcoin-screen/receive-usd.tsx [hunk 5]
```diff
@@ -145,6 +146,45 @@ const ReceiveUsd = () => {
   const { lnUpdate } = useSubscriptionUpdates()
   const [showMemoInput, setShowMemoInput] = useState(false)
   const [showAmountInput, setShowAmountInput] = useState(false)
+  const { timeLeft, startCountdownTimer, resetCountdownTimer } = useCountdownTimer()
+  const timeUntilInvoiceExpires = useMemo(() => {
+    if (invoice) {
+      return (
+        getLightningInvoiceExpiryTime(decodeInvoiceString(invoice.paymentRequest)) -
```
Comment (UncleSamtoshi) [inline app/screens/receive-bitcoin-screen/receive-usd.tsx:153]: This value could be negative, and your hook doesnt currently handle negative values.

File: app/hooks/use-countdown-timer.ts [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+        }
+      }
+
+      return () => {
+        clearInterval(interval)
+      }
+    }
+    // We need to return from all code paths but we only need a callback if an interval is set so returning undefined is fine
+    return undefined
+  }, [timeLeft, completedCallback])
```
Comment (UncleSamtoshi) [inline app/hooks/use-countdown-timer.ts:38]: Should ```setTimeLeft``` be a part of the dependency list?

File: app/screens/receive-bitcoin-screen/receive-usd.tsx [hunk 7]
```diff
@@ -145,6 +146,45 @@ const ReceiveUsd = () => {
   const { lnUpdate } = useSubscriptionUpdates()
   const [showMemoInput, setShowMemoInput] = useState(false)
   const [showAmountInput, setShowAmountInput] = useState(false)
+  const { timeLeft, startCountdownTimer, resetCountdownTimer } = useCountdownTimer()
+  const timeUntilInvoiceExpires = useMemo(() => {
```
Comment (UncleSamtoshi) [inline app/screens/receive-bitcoin-screen/receive-usd.tsx:150]: I think ```timeUntilInvoiceExpires``` is a misleading name, because on subsequent renders it is no longer actually the time until invoice expires. You can get rid of lines 150-158 all together and add that logic to the effect in line 179 while changing line 187 to just depend on the invoice.

File: app/screens/receive-bitcoin-screen/receive-usd.tsx [hunk 8]
```diff
@@ -145,6 +146,45 @@ const ReceiveUsd = () => {
...
+    if (invoice) {
+      return (
+        getLightningInvoiceExpiryTime(decodeInvoiceString(invoice.paymentRequest)) -
+        Math.round(Date.now() / 1000)
+      )
+    }
+    return NaN
+  }, [invoice])
+
+  useEffect(() => {
```
Comment (UncleSamtoshi) [inline app/screens/receive-bitcoin-screen/receive-usd.tsx:160]: You don't have to make this change, but one way to avoid having to keep the timer in sync like this would be to implement the hook by storing the expiration of the timer, and then each second calculating how much time is left, vs the current implementation where you store how much time is left but then it can get out of sync if you leave the app.

File: app/screens/receive-bitcoin-screen/receive-usd.tsx (hunk 1 above)
Comment (daviroo) [reply app/screens/receive-bitcoin-screen/receive-usd.tsx:176]: The intention is for this `useEffect` to only run once when the component mounts as it is setting a callback for when the appstate changes and doesn't need to be rerun when any of the dependencies change.

File: app/screens/receive-bitcoin-screen/receive-usd.tsx (hunk 7 above)
Comment (daviroo) [reply app/screens/receive-bitcoin-screen/receive-usd.tsx:150]: Yeah I agree and I have made the change.

File: app/screens/receive-bitcoin-screen/receive-usd.tsx (hunk 5 above)
Comment (daviroo) [reply app/screens/receive-bitcoin-screen/receive-usd.tsx:153]: I guess in practice this could only happen if the app came back from background and the invoice had already expired - but you're right we should just set the invoice as expired if the value is negative and not start the timer.

File: app/hooks/use-countdown-timer.ts (hunk 3 above)
Comment (daviroo) [reply app/hooks/use-countdown-timer.ts:58]: Done

File: app/screens/receive-bitcoin-screen/receive-usd.tsx (hunk 1 above)
Comment (daviroo) [reply app/screens/receive-bitcoin-screen/receive-usd.tsx]: I've changed the way it works so now the hook utilises the dependencies.

File: app/hooks/use-countdown-timer.ts (hunk 2 above)
Comment (daviroo) [reply app/hooks/use-countdown-timer.ts]: Yup changed

File: app/hooks/use-countdown-timer.ts (hunk 4 above)
Comment (daviroo) [reply app/hooks/use-countdown-timer.ts:47]: Yup agreed, changed

File: app/hooks/use-countdown-timer.ts (hunk 6 above)
Comment (daviroo) [reply app/hooks/use-countdown-timer.ts]: Yeah agreed - have added it to the dependency list

File: app/screens/receive-bitcoin-screen/receive-usd.tsx (hunk 8 above)
Comment (daviroo) [reply app/screens/receive-bitcoin-screen/receive-usd.tsx:158]: I made your suggested change.

**Comment by daviroo** [comment]
@UncleSamtoshi I've made your suggested change and responded to your comments.  I'll leave the comments for you to resolve if you feel like I've addressed them appropriately.

**Review by UncleSamtoshi — APPROVED** [review]
